# Generated by Django 5.0.4 on 2024-04-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastepointapp', '0002_billinginfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinginfo',
            old_name='billing_country',
            new_name='billing_zip_code',
        ),
    ]
