# Generated by Django 5.0.4 on 2024-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastepointapp', '0003_rename_billing_country_billinginfo_billing_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='billing_city',
            field=models.CharField(default='No City', max_length=200),
        ),
    ]
